/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inmobiliariafront.ventanas;
import inmobiliaria.controladores.ControladorLogin;
import inmobiliaria.vista.VistaLogin;
import java.awt.Color;

/**
 *
 * @author Ulx
 */
public class VentanaInicio extends javax.swing.JFrame implements VistaLogin{

    private final ControladorLogin controlador;
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setTitle("Inicio sesion inmobiliaria");
        setSize(700,360);
        setLocationRelativeTo(null);
        this.controlador = new ControladorLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTextoUsuario = new javax.swing.JTextField();
        JTextoPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        JTextoExito = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTextoUsuario.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        JTextoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JTextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(JTextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, 30));

        JTextoPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JTextoPassword.setToolTipText("Password");
        JTextoPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTextoPassword.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(JTextoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 150, 30));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));
        jPanel1.add(JTextoExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 270, 340));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setToolTipText("");
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 450, 300));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 420, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextoUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String user = JTextoUsuario.getText();
       String password = JTextoPassword.getText();
       controlador.loginExitoso(user, password);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTextoExito;
    private javax.swing.JPasswordField JTextoPassword;
    private javax.swing.JTextField JTextoUsuario;
    private javax.swing.JPanel Login;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensaje(String mensaje) {
        JTextoExito.setText(mensaje);
        JTextoExito.setForeground(mensaje.equals("Login exitoso") ? Color.GREEN : Color.RED);
    }

    @Override
    public void abrirVentanaPrincipal() {
        this.setVisible(false); // Ocultamos la ventana de login

        // Crear y mostrar la nueva ventana (por ejemplo, un panel principal)
        VentanaMenu menu = new VentanaMenu();
        menu.setVisible(true); // Hacemos visible la nueva ventana
    }
}
